name: Auto Merge Pull Requests by Henry Bartz

on:
  pull_request:
    types: [opened, labeled, reopened, synchronize]

jobs:
  automerge:
    if: github.actor == 'BuggzRadio-AZD'  # <-- Replace with your GitHub username if different
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_LABELS: ""  # Leave empty if you don’t want to require a label
